### ISSUE TITLE
Lightspeed 's' search stopped working

### ISSUE THREAD

**Issue by drusmanbashir** [ggandor/lightspeed.nvim#135] opened 2022-03-04 15:15 UTC
Hi, Any time I press s or S, i get the following error:
![Screenshot 2022-03-04 15:15:17](https://user-images.githubusercontent.com/5282314/156789257-6ea832f4-9462-4870-bd4b-d2ab66bb2d31.png)

f and F work fine though

**Comment by ggandor** [comment] 2022-03-04 17:43
Duplicate of #131

**Closed by ggandor** 2022-03-04 17:43 UTC
Labels: duplicate
