### ISSUE TITLE
Resizing the window during an action moves the view to the actual cursor position

### ISSUE THREAD

**Issue by booperlv** [ggandor/lightspeed.nvim#20] opened 2021-07-02 17:31 UTC
Hello!
I understand that this the cursor being moved to this "blank portion"(for lack of a better term) is intended behavior, but how can the resizing of the editor itself be handled?

Here's a video showing the said behavior using 2 character search and f:

https://user-images.githubusercontent.com/65604882/124266838-0dd4d380-db6a-11eb-8f39-4e9855637631.mp4

I have a few of ideas on how it could work, simplest of them being:
```
VimResize autocommand on start -> winrestview(winsaveview-saved-somewhere) -> disable autocommand on end
```
But then how best would it be best to implement the saving of window view?
Since there is no VimResizePre auto command, Would it be a CursorMoved autocommand that enables when lightspeed is active? Or would it be better to use a completely different approach?

Sorry for the questions, curious about what approach others would take :D

**Comment by ggandor** [comment] 2021-07-04 10:59
Well, resizing the window in the middle of a 2-char search would break the plugin anyway, by design, since we are labeling matches inside the window. (Who in their right mind would want to do this in the first place? :D) As for the question, I thought forcing a `:redraw` on `VimResize` _might_ do something, but apparently it doesn't. I'm not sure that going down to the command line counts as a `CursorMoved` event, but I might be mistaken.

Anyway, I'm closing this now, but if you (or anyone else) will have some technical insights about this issue (i.e. the content disappearing on resize), feel free to share it here.

**Closed by ggandor** 2021-07-04 10:59 UTC

**Comment by ggandor** [comment] 2021-07-06 16:27
Maybe you could experiment with saving the window on `CmdlineEnter`. Also make sure that you exclude the cursor fields (`lnum`, `col`) from the dictionary passed to `winrestview`, as `winsaveview` saves cursor state too by default.
