### ISSUE TITLE
[Bug]: Error when pressing s

### ISSUE THREAD

**Issue by matthis-k** [ggandor/lightspeed.nvim#143] opened 2022-04-09 09:35 UTC
Here my config for the plugin (defaults) and the error message when pressing `s`:

![screenshot_2022-04-09_11-31-14_148371849](https://user-images.githubusercontent.com/69082876/162566128-b00928dc-1d2b-46ae-b0d9-545add8a788e.png)

**Comment by ggandor** [comment] 2022-04-09 10:48
Hi! You need to update Neovim if you're using 0.7+ (see https://github.com/ggandor/lightspeed.nvim/issues/131).

Duplicate of #131

Remarks:
- Do not copy-paste the example snippet from the README: https://github.com/ggandor/lightspeed.nvim/issues/115#issuecomment-999723604
- If you already saved the required module into a variable in the line `local status_ok, lightspeed = ...`, then later you can just say `lightspeed.setup { ... }`, instead of `require('lightspeed').setup { ... }`.

**Closed by ggandor** 2022-04-09 10:48 UTC
