### ISSUE TITLE
Leading `tab`s compromise the calculation of horizontal bounds

### ISSUE THREAD

**Issue by JSchrtke** [ggandor/lightspeed.nvim#98] opened 2021-12-02 14:42 UTC
Pressing `s/` yields the following result

![image](https://user-images.githubusercontent.com/31078741/144441646-87aa691d-6f49-4cc7-827d-e52541d04e54.png)

As you can see, only one occurence of `//` gets highlighted. However, if I `set list`, the result is this

![image](https://user-images.githubusercontent.com/31078741/144441925-7b41e141-0118-45ce-bb5d-6c9e7314b355.png)

With `set list` on, everything works fine. Turning it off again produces the buggy first behaviour again.

Notice how the first occurence of `//` is prefixed by a `space`, the others by a `tab`. I thought this might be the sole reason for this bug, but I wasn't able to reproduce that behaviour in a simple text file.

So I copied a small chunk of the C code into a text file, in which I am able  to reproduce that behaviour. I'm attaching said file to this issue so you can use it for debugging.

This doesn't only happen when targeting the `//`, the same issue persists targeting the lines starting with `sConfig`.

Pressing `ss` with `set nolist` yields

![image](https://user-images.githubusercontent.com/31078741/144443243-38c00bdb-39df-4ecb-8d7f-f9f634329e57.png)

And again, with `set list` it behaves like expected.

![image](https://user-images.githubusercontent.com/31078741/144443375-6e2ce48d-a239-470d-a657-691f1bb23547.png)

My lightspeed config is completely stock, I've only installed it but changed no settings.

[lightspeed_bug_repro.txt](https://github.com/ggandor/lightspeed.nvim/files/7642769/lightspeed_bug_repro.txt)

Edit: 
```
NVIM v0.6.1-dev+656-g84784a839
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by js@tmt

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
```
~/temp ❯ [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```

**Comment by ggandor** [comment] 2021-12-04 15:08
Thanks for the thorough bug report! I cannot reproduce this. I tried this with `nvim -u NONE` + manually sourcing lightspeed.lua too, and it still works, so it's probably something in your config. That might still indicate some bug to be fixed on our side, but this is good news, because sooner or later it can be hunted down then. I have no idea where to start though.

**Comment by JSchrtke** [comment] 2021-12-04 17:09
Okay, I got it.

1.:
Use the following config

```vim
call plug#begin('~/.vim/plugged')
Plug 'ggandor/lightspeed.nvim'
call plug#end()
setlocal nowrap
```
2.:
`nvim lightspeed_bug_repro.txt`

3.:
press `ss`

This will yield the following result:

![image](https://user-images.githubusercontent.com/31078741/144718214-27265c8e-425f-4e6b-b4cf-78338313be46.png)

4.:
`set list` make lightspeed work as expected, ie:

![image](https://user-images.githubusercontent.com/31078741/144718235-6a467a3a-07c1-460a-b1aa-ac144b1881eb.png)

**Comment by ggandor** [comment] 2021-12-04 19:21
Ouch, I can reproduce this now. Indeed, it has something to do with `tab`s, if you replace them with spaces, works fine.

**Comment by JSchrtke** [comment] 2021-12-04 19:51
yeah, seems it does. I tried reproducing this artificially though and couldn't do it so far. I'm now working with the file I uploaded here and trying to have the smallest amount of content that triggers the bug. It's not as simple as having mixed indents, I tried that already.

Do you have any idea what might be causing this?

**Comment by JSchrtke** [comment] 2021-12-04 20:00
Okay, so, it get's better/worse. Depends how you look at it. With this file, place the cursor at the beginning of the first line. Then press `s/`. 
That causes my entire neovim instance to lock up until I press `ctrl+c`. Can you reproduce that aswell?

[minimal_repro.txt](https://github.com/ggandor/lightspeed.nvim/files/7654598/minimal_repro.txt)

**Comment by ggandor** [comment] 2021-12-04 21:25
> Can you reproduce that aswell?

No :) But now I cannot reproduce again on the original file either...

> Do you have any idea what might be causing this?

A very wild guess, might be a total misfire: this could be related to the calculation of the leftmost editable screen column (we should ignore the fold column, line numbers, etc.), maybe the search loop skips those matches for some reason? Does the problem appear anywhere in the middle of the window, when the target is not in the first few columns?

**Comment by ggandor** [comment] 2021-12-04 21:41
Okay, I got this, just as I thought. The root of the problem is that we do a hack to calculate the "gutter" width, by doing a `norm! 0`, and check the column we're in, but if the first char is a `tab`, that will put the cursor to the last (screen) column the `tab` occupies, e.g. if `tabstop`=8, then to the 8th column in the actual editable area, not the 0th, and that messes up the whole subsequent calculation, so the first 8 char will be skipped on each line.

**Comment by JSchrtke** [comment] 2021-12-04 21:42
ah, the ninja edit, now my comment makes no sense :P

**Comment by JSchrtke** [comment] 2021-12-04 21:44
> Okay, I got this, just as I thought. The root of the problem is that we do a hack to calculate the "gutter" width, by doing a `norm! 0`, and check the column we're in, but if the first char is a `tab`, that will put the cursor to the last (screen) column the `tab` occupies, e.g. if `tabstop`=8, then to the 8th column in the actual editable area, not the 0th, and that messes up the whole subsequent calculation, so the first 8 char will be skipped on each line.

Alright, sounds like you know what to look for. Let me know if I need to to anything.

I was just in the middle of testing to confirm that the `tabstop` setting does influence this somehow. But you are right, it does.

**Comment by ggandor** [comment] 2021-12-04 21:50
> Alright, sounds like you know what to look for.

Yeah, at the very latest, it will be fixed when the improved `getwininfo()` will work properly, and I can use that to get rid of the `norm! 0` hack (in theory, on 0.6. it should be able to return the necessary info in the `textoff` field, but it doesn't work for me at the moment).

**Closed** 2021-12-06 10:11 UTC
Labels: bug

**Comment by JSchrtke** [comment] 2021-12-06 18:03
Seems to work fine so far, I've used this at work today and haven't encountered any issues yet.
