### ISSUE TITLE
`scrolloff` is not reverted back to its old value on exiting

### ISSUE THREAD

**Issue by jmlucjav** [ggandor/lightspeed.nvim#73] opened 2021-11-04 14:09 UTC
Hi,

I have 

scrolloff=999

but after a while, I notice it is set to 0. I have searched over all my plugins etc, and lightspeed is a suspect. I saw this https://github.com/ggandor/lightspeed.nvim/issues/27 and it look related. I understand this should be temporary, but it seems something is not ok and scrolloff stays at 0. 

Is there anything I could do to verify this?

thanks

**Comment by ggandor** [comment] 2021-11-04 17:23
Hi! Yes, I suspect we are the guilty ones. It should be temporary of course, any `exit` form (those are macros handling cleanup stuff) triggers autocommands that restore these editor options unconditionally - the only possible explanation is that somehow I've missed a possible return point (the flow is indeed quite complicated in `sx`.) I'll look into this ASAP.

In the meanwhile, it would be great if you could help me narrow it down, when exactly does this occur? (Successful jump or early exit, e.g. `C-c`-ing? Using a shortcut? After switching match groups? Etc.)

**Comment by jmlucjav** [comment] 2021-11-04 20:34
Hi,

I am trying to narrow it down but for now I could not repro it.

FYI, in case it helps, I have these in my init.vim:

```
" lightspeed ----------------------------------------------------------- 
"make native ;/,; for f/t next
fun! s:RepeatFt(reverse)
  lua require'lightspeed'.ft['instant-repeat?'] = true
  lua require'lightspeed'.ft:to(vim.api.nvim_eval('a:reverse'),require'lightspeed'.ft['prev-t-like?'])
endfun
nnoremap <silent> ; <cmd>call <SID>RepeatFt(v:false)<cr>
xnoremap <silent> ; <cmd>call <SID>RepeatFt(v:false)<cr>
nnoremap <silent> <leader>;  <cmd>call <SID>RepeatFt(v:true)<cr>
xnoremap <silent> <leader>; <cmd>call <SID>RepeatFt(v:true)<cr>
```

**Comment by ggandor** [comment] 2021-11-05 08:55
Hmm, it's great that you shared the config - it seems you're using a pretty old version, this workaround is not valid anymore, [we have `<Plug>` keys for ;/, now](https://github.com/ggandor/lightspeed.nvim#keymaps). Would you test if the issue still persists using the most recent commit? Because I fixed a relevant issue [recently](https://github.com/ggandor/lightspeed.nvim/commit/d39dad6519aefee253dcf0a071f67cefc24809d3), I'm 99% sure that is the one we're looking for.

**Comment by jmlucjav** [comment] 2021-11-05 21:25
version is about a couple of months or so I guess, but yeah, I just updated, and will ping here if I see the issue again in the following days.

Thanks!

**Comment by ggandor** [comment] 2021-11-16 16:22
I'm closing this now, we can reopen anytime if needed.

**Comment by gimerstedt** [comment] 2021-11-17 12:43
ah, this is what's causing my scrolloff to change. i am getting this with 3140e02e23305083b5f5e79b5d83ca480ee64b40 so i assume this is still an issue.

**Comment by ggandor** [comment] 2021-11-17 16:24
> 
> 
> ah, this is what's causing my scrolloff to change. i am getting this with [3140e02](https://github.com/ggandor/lightspeed.nvim/commit/3140e02e23305083b5f5e79b5d83ca480ee64b40) so i assume this is still an issue.

Okay, then the task is the same as before: try to narrow it down, if you're able to, because now I really have no idea offhand where the potential "leak" could be.

**Comment by gimerstedt** [comment] 2021-11-17 16:47
had the same experience as @jmlucjav and was unable to replicate it when trying, so i have no idea what it could be. i have not experienced it before and the only thing added was this plugin (since removed due to wontfixes) so i'm 99% certain it was caused by it. best of luck.

**Comment by ggandor** [comment] 2021-11-17 17:09
Which wontfixes were the deal-breakers? (Just curious.)

**Comment by gimerstedt** [comment] 2021-11-17 17:15
> 
> 
> Which wontfixes were the deal-breakers? (Just curious.)

omni-direction would be nice but not a deal breaker (https://github.com/ggandor/lightspeed.nvim/issues/8)
smartcase is for sure a deal breaker (https://github.com/ggandor/lightspeed.nvim/issues/64)

**Comment by ggandor** [comment] 2021-11-17 17:32
Okay, thanks 😊 Yeah, nothing can be done with #64. A pity though.

**Comment by ggandor** [comment] 2021-12-07 12:13
A note for everyone experiencing this issue: the problem can be circumvented by "manually" setting the value back to the preferred one, hardcoded into an autocommand, on exiting Lightspeed.
```vim
" + the usual augroup boilerplate
autocmd User LightspeedLeave set scrolloff=...
```

**Comment by ggandor** [comment] 2021-12-19 12:05
@gimerstedt Case-insensitive search [is an option now](https://github.com/ggandor/lightspeed.nvim/commit/b6ccf8207cc1384677a65a3527aed3020a08ec91).

**Closed** 2022-03-09 23:53 UTC
Labels: bug, has-workaround
